Assignment I



```
# This is formatted as code
```

913119205012

Hailly J

In [ ]:
#1.
s = "Hi there Sam!"
a = s.split()
#split() split the string to list
print(a)

['Hi', 'there', 'Sam!']


In [ ]:
#2.
planet = "Earth"
diameter = 12742
print("The diameter of %s is %d Kilometers." % (planet, diameter))

The diameter of Earth is 12742 Kilometers.


In [ ]:
#3.
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [ ]:
#4.
import numpy as np
np.ones(10) * 0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#5.
import numpy as np
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#6.
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array) 

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


In [ ]:
#7.
import numpy as np
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
joined = np.concatenate((array1, array2))
print(joined)

[1 2 3 4 5 6]


In [ ]:
#8.
import pandas as pd
data = [['mahi', 10], ['sindhu', 15], ['hailly', 14]]
df = pd.DataFrame(data, columns=['Name', 'Age'])
df

Name  Age
0    mahi   10
1  sindhu   15
2  hailly   14

In [ ]:
#9.
import datetime
import pandas as pd
test_date = datetime.datetime.strptime("01-1-2023", "%d-%m-%Y")
K = 41
date_generated = pd.date_range(test_date, periods=K)
print(date_generated.strftime("%d-%m-%Y"))

Index(['01-01-2023', '02-01-2023', '03-01-2023', '04-01-2023', '05-01-2023',
       '06-01-2023', '07-01-2023', '08-01-2023', '09-01-2023', '10-01-2023',
       '11-01-2023', '12-01-2023', '13-01-2023', '14-01-2023', '15-01-2023',
       '16-01-2023', '17-01-2023', '18-01-2023', '19-01-2023', '20-01-2023',
       '21-01-2023', '22-01-2023', '23-01-2023', '24-01-2023', '25-01-2023',
       '26-01-2023', '27-01-2023', '28-01-2023', '29-01-2023', '30-01-2023',
       '31-01-2023', '01-02-2023', '02-02-2023', '03-02-2023', '04-02-2023',
       '05-02-2023', '06-02-2023', '07-02-2023', '08-02-2023', '09-02-2023',
       '10-02-2023'],
      dtype='object')


In [ ]:
#10.
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame.from_dict(lists) 
df

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24